export const AppActions = {
    SET_SELECTED_MATTRESS: "SET_SELECTED_MATTRESS",
    ADD_TO_SHOPPING_CART: "ADD_TO_SHOPPING_CART",
    REMOVE_FROM_SHOPPING_CART: "REMOVE_FROM_SHOPPING_CART",
    SUBTRACT_SHOPPING_CART_ITEM: "REDUCE_SHOPPING_CART_ITEM",
};
